remote_theme: carlosperate/jekyll-theme-rtd
title: Documentation
description: This website its for documentation of my projects.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/vipnunes/jekyll-theme-rtd"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
